"""The run ledger (spec §30) -- the only place wall-clock time is allowed.

Reports must be byte-identical between two runs over the same input, so no
timestamp may reach a report.  Cost, duration and cache telemetry still have to
be recorded somewhere, and that somewhere is here: a per-run ledger file that
nothing hashes, asserts or diffs.

``new_run_id`` is intentionally **not** deterministic -- two runs are two runs
-- which is exactly why the run id lives in the ledger and is passed into the
report by the caller rather than generated by a report renderer.
"""

from __future__ import annotations

import math
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from ..util import read_json, short_hash, write_json


@dataclass
class ToolTiming:
    provider: str
    duration_ms: int = 0
    status: str = "OK"

    def to_dict(self) -> dict[str, Any]:
        return {
            "provider": self.provider,
            "duration_ms": self.duration_ms,
            "status": self.status,
        }


@dataclass
class RunLedger:
    run_id: str = ""
    repo: str = ""
    commit: Optional[str] = None
    base: Optional[str] = None
    mode: str = "diff"
    started_at: str = ""
    duration_ms: int = 0
    tool_duration: list[ToolTiming] = field(default_factory=list)
    llm_calls: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    cache_hit: float = 0.0
    findings: int = 0
    dedup_ratio: float = 0.0
    gate: Optional[str] = None
    errors: list[dict[str, Any]] = field(default_factory=list)

    # ------------------------------------------------------------------ api

    def add_tool(self, provider: str, duration_ms: int, status: str) -> None:
        self.tool_duration.append(
            ToolTiming(provider=str(provider), duration_ms=int(duration_ms), status=str(status))
        )

    def add_llm(self, calls: int, input_tokens: int, output_tokens: int) -> None:
        self.llm_calls += int(calls)
        self.input_tokens += int(input_tokens)
        self.output_tokens += int(output_tokens)

    def to_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "repo": self.repo,
            "commit": self.commit,
            "base": self.base,
            "mode": self.mode,
            "started_at": self.started_at,
            "duration_ms": self.duration_ms,
            "tool_duration": [t.to_dict() for t in self.tool_duration],
            "llm_calls": self.llm_calls,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "cache_hit": self.cache_hit,
            "findings": self.findings,
            "dedup_ratio": self.dedup_ratio,
            "gate": self.gate,
            "errors": [dict(e) for e in self.errors],
            "error_count": len(self.errors),
        }

    def write(self, path: Path | str) -> None:
        write_json(path, self.to_dict())


def new_run_id(repo_root: Path | str, *, mode: str, commit: Optional[str]) -> str:
    """A unique, sortable run id.

    Unique -- not deterministic -- because two runs of the same commit must not
    overwrite each other's artefacts.  It is deliberately *not* derived from
    the report content and never feeds a hash or an assertion.
    """
    stamp = time.strftime("%Y%m%dT%H%M%S", time.localtime())
    entropy = short_hash(
        str(repo_root),
        str(mode),
        str(commit or ""),
        str(time.time_ns()),
        str(os.getpid()),
        length=6,
    )
    return f"{stamp}-{entropy}"


# --------------------------------------------------------------------------
# aggregate statistics
# --------------------------------------------------------------------------


def percentile(values: list[float], p: float) -> float:
    """Linear-interpolated percentile; empty input yields 0.0."""
    if not values:
        return 0.0
    xs = sorted(float(v) for v in values)
    if len(xs) == 1:
        return xs[0]
    if p <= 0.0:
        return xs[0]
    if p >= 100.0:
        return xs[-1]
    position = (len(xs) - 1) * (p / 100.0)
    low = int(math.floor(position))
    high = int(math.ceil(position))
    if low == high:
        return xs[low]
    return xs[low] + (xs[high] - xs[low]) * (position - low)


def _round(value: float, digits: int) -> float:
    return round(float(value), digits)


def _ledger_files(directory: Path) -> list[Path]:
    """Ledgers live either flat in the directory or one level down.

    The orchestrator writes ``<run_dir>/<run_id>/ledger.json``, while ad-hoc
    callers write ``<dir>/ledger.json``; both have to be found, and
    ``<runs>/latest.json`` (a pointer, not a ledger) is filtered out later by
    the ``run_id`` check.
    """
    seen: dict[str, Path] = {}
    for pattern in ("*.json", "*/ledger.json", "*/*.json"):
        for candidate in directory.glob(pattern):
            if candidate.is_file():
                seen[str(candidate)] = candidate
    return [seen[k] for k in sorted(seen)]


def summarize_ledgers(ledger_dir: Path | str) -> dict[str, Any]:
    """Aggregate every ledger under a runs directory.

    Degrades honestly: unreadable or malformed ledgers are counted in
    ``skipped`` instead of being silently treated as zero-cost runs.
    """
    directory = Path(ledger_dir)
    ledgers: list[dict[str, Any]] = []
    skipped = 0
    if directory.is_dir():
        for path in _ledger_files(directory):
            data = read_json(path, default=None)
            if isinstance(data, dict) and "run_id" in data:
                ledgers.append(data)
            else:
                skipped += 1

    if not ledgers:
        return {
            "runs": 0,
            "skipped": skipped,
            "avg_input_tokens": 0.0,
            "avg_output_tokens": 0.0,
            "p50_ms": 0.0,
            "p95_ms": 0.0,
            "tool_duration": {},
            "cache_hit_ratio": 0.0,
            "gate_histogram": {},
            "new_debt_per_run": {"avg": 0.0, "total": 0, "per_run": {}},
        }

    durations = [float(x.get("duration_ms", 0) or 0) for x in ledgers]
    inputs = [float(x.get("input_tokens", 0) or 0) for x in ledgers]
    outputs = [float(x.get("output_tokens", 0) or 0) for x in ledgers]
    cache_hits = [float(x.get("cache_hit", 0.0) or 0.0) for x in ledgers]

    tool_samples: dict[str, list[float]] = {}
    for ledger in ledgers:
        for timing in ledger.get("tool_duration") or []:
            if not isinstance(timing, dict):
                continue
            provider = str(timing.get("provider", "unknown"))
            tool_samples.setdefault(provider, []).append(
                float(timing.get("duration_ms", 0) or 0)
            )

    gate_histogram: dict[str, int] = {}
    for ledger in ledgers:
        verdict = ledger.get("gate")
        if verdict is None:
            continue
        gate_histogram[str(verdict)] = gate_histogram.get(str(verdict), 0) + 1

    # The ledger records the post-dedup finding count; with no separate
    # new-debt counter that is the most honest proxy available.
    per_run = {
        str(ledger.get("run_id", "")): int(ledger.get("findings", 0) or 0)
        for ledger in ledgers
    }
    debt_values = list(per_run.values())

    return {
        "runs": len(ledgers),
        "skipped": skipped,
        "avg_input_tokens": _round(sum(inputs) / len(inputs), 1),
        "avg_output_tokens": _round(sum(outputs) / len(outputs), 1),
        "p50_ms": _round(percentile(durations, 50), 1),
        "p95_ms": _round(percentile(durations, 95), 1),
        "tool_duration": {
            provider: {
                "avg_ms": _round(sum(samples) / len(samples), 1),
                "p95_ms": _round(percentile(samples, 95), 1),
                "runs": len(samples),
            }
            for provider, samples in sorted(tool_samples.items())
        },
        "cache_hit_ratio": _round(sum(cache_hits) / len(cache_hits), 4),
        "gate_histogram": dict(sorted(gate_histogram.items())),
        "new_debt_per_run": {
            "avg": _round(sum(debt_values) / len(debt_values), 1),
            "total": sum(debt_values),
            "per_run": dict(sorted(per_run.items())),
        },
    }
